"""Create tables users, charities, donations, beneficiaries,inventory

Revision ID: 5b7bdc370ab6
Revises: 
Create Date: 2023-08-03 08:19:51.252031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7bdc370ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('amount_received', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('charity_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('beneficiaries',
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_name', sa.String(), nullable=False),
    sa.Column('story', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.PrimaryKeyConstraint('beneficiary_id')
    )
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('donation_date', sa.DateTime(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('schedule_start_date', sa.DateTime(), nullable=True),
    sa.Column('schedule_end_date', sa.DateTime(), nullable=True),
    sa.Column('schedule_frequency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('donations')
    op.drop_table('beneficiaries')
    op.drop_table('users')
    op.drop_table('charities')
    # ### end Alembic commands ###
