"""empty message

Revision ID: bfc8811bc793
Revises: f4c8c3a6010e
Create Date: 2023-08-08 21:43:54.702437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc8811bc793'
down_revision = 'f4c8c3a6010e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_name')
        batch_op.drop_column('official_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
